# Generated by Django 2.2.5 on 2020-08-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume/%Y/%m/%d/'),
        ),
    ]
